[package]
name = "os-isolated"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.4"
os-shared = { path = "../os-shared" }

[dev-dependencies]
criterion = "0.5.1"

[profile.release]
lto = true
debug = true

[[bench]]
name = "iteration"
harness = false
