[package]
name = "os-impl"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "1.0.0"
rppal = { version = "0.17.1", features = ["hal"] }
log = "0.4.21"
env_logger = "0.11.3"
pid-ctrl = "0.1.4"
fugit = "0.3.7"
