[package]
name = "bcm2711-hal"
version = "0.1.0"
edition = "2021"

[dependencies]
aarch64-cpu = "9.4.0"
bcm2711-lpa = { version = "0.4.0", features = ["critical-section"] }
critical-section = "1.1.2"
embedded-hal = "1.0.0"
