[package]
name = "os-shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "1.0.0"
pid-ctrl = "0.1.4"
rppal = { version = "0.17.1", features = ["hal"] }
